### ISSUE TITLE
When initialising on windows, an error on box loading happens

### ISSUE THREAD

**Issue by bakhyeonjae** [bakhyeonjae/Athena#12]
(base) C:\Users\박현재\Desktop\Athena\Athena-dev\Athena-dev\src\frontend>python athena.py
Traceback (most recent call last):
  File "athena.py", line 154, in <module>
    mywin = TopWindow()
  File "athena.py", line 130, in __init__
    self.tree = TreeWidget(self.frame,self.viewInfo,SystemConfig.getRepository(),'Cloud Workspace')
  File "athena.py", line 77, in __init__
    categories = self.getSubDir(self.boxDir)
  File "athena.py", line 98, in getSubDir
    sub_dir = list(list(next(os.walk(pathName))[1]))
StopIteration

**Comment by bakhyeonjae** [comment]
That is caused by hard-coded path names

**Comment by bakhyeonjae** [comment]
Find home directory and config

from pathlib import Path
str(Path.home())

**Comment by bakhyeonjae** [comment]
fixed.
